# Generated by Django 4.0.1 on 2022-01-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_applications_consent_reviews_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='consent',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='consent',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
