# Generated by Django 4.0.1 on 2022-01-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_applications_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='email',
            field=models.EmailField(help_text='Укажите ваш действующий Email', max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='mobile',
            field=models.CharField(help_text='Укажите в формате: +7 000 000-00-00', max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name_org',
            field=models.CharField(max_length=100, verbose_name='Организация'),
        ),
    ]
