# Generated by Django 4.0.1 on 2022-01-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_applications_add_inf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='email',
            field=models.EmailField(blank='True', help_text='Укажите ваш действующий Email', max_length=100, verbose_name='Почта'),
        ),
    ]
