# Generated by Django 4.0.1 on 2022-02-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reviews_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='email',
            field=models.EmailField(blank='True', max_length=100, verbose_name='Почта'),
        ),
    ]
